new_opt=[                        
'read lhz.ah                    '
'rm NWAO CHTO GUMO LZH TATO BJI '
'sort delta                     '
'phas P                         '
'widt -200 1000                 '
'cut 0                          '
'deme                           '
'inte                           '
'deme                           '
'tape .1                        '
'deco l .000001                 '
'tt P pP sP                     '
'tt S sS pS                     '
'tt PP SS PcP ScP               '
'corr                           '
'plot 1                         '
'plot 1                         '
'copy 1 3                       '
'widt 0 50                      '
'phas sPP                       '
'cut 0                          '
'plot 1                         '
'                               '
'copy 3 1                       '
'cut 1                          '
'plot 1                         '
'hilb                           '
'plot 1                         '
'xwin .3 20 1                   '
'plot 1                         '
'plot 1                         '
'xcor                           '
'fs 3 2                         '
'plot 1                         '
'plot 1                         '
'                               '
'fs 3 2                         '
];                               
