new_opt=[                        
'read lhz.ah                    '
'rm NWAO CHTO GUMO LZH TATO BJI '
'rm MAJO HIA                    '
'sort delta                     '
'phas P                         '
'widt -200 500                  '
'cut 0                          '
'deme                           '
'inte                           '
'deme                           '
'tape .1                        '
'deco l                         '
'widt -100 500                  '
'cut 1                          '
'copy 1 2                       '
'widt 0 40                      '
'cut 1                          '
'copy 1 3                       '
'copy 2 1                       '
'widt -100 500                  '
'stop                           '
];                               
