new_opt=[                                
'yaxi E                                 '
'orient tall                            '
'read lhz.ah                            '
'corr                                   '
'rm NWAO CHTO GUMO LZH TATO BJI HIA MAJO'
'rm noinstr                             '
'phas P                                 '
'widt -300 900                          '
'cut 0                                  '
'sort 1 delta                           '
'deme                                   '
'tt P PP PcP PKPdf PKPab                '
'tt S SS ScS SKSac SKKS                 '
'tt PcS ScP pP sP pPP                   '
'tt sPP sS pS sSS pSS                   '
'tt SP PS pSP sSP pPS                   '
'tt sPS pPKPdf sPKPdf                   '
'tt pPKPab sPKPab  PKKP                 '
'plot 0                                 '
'plot 1                                 '
'who                                    '
];                                       
