new_opt=[                               
'read lh.t                             '
'titl LHT 900512 Kuril, h=606          '
'sort delta                            '
'tt sScS                               '
'tt S sS ScS SKSac SS                  '
'phas S                                '
'widt -240 800                         '
'cut 0                                 '
'plot 1                                '
'plot 1                                '
'copy 1 2                              '
'inte                                  '
'plot 1                                '
'deme                                  '
'tape .1                               '
'deco l .000001                        '
'copy 1 3                              '
'plot 1                                '
'scal -.07                             '
'plot                                  '
'plot 1                                '
'plot 1                                '
'                                      '
'copy 1 3                              '
'plot 1                                '
'xwin .1 1                             '
'plot 1                                '
'                                      '
'widt -120 600                         '
'cut 1                                 '
'plot 1                                '
'scal -.1                              '
'plot 1                                '
'xwin .3 20 1                          '
'plot 1                                '
'                                      '
'xwin 0 20 1                           '
'plot 1                                '
'xwin .2 1                             '
'plot 1                                '
'                                      '
'writ lh.t.cl                          '
'copy 1 3                              '
'widt -30 90                           '
'cut 1                                 '
'plot 1                                '
'fs 3 2                                '
'plot 1                                '
'copy 1 2                              '
'xcor 4                                '
'plot 1                                '
'xcor 4                                '
'plot 1                                '
'fs 3 2                                '
'plot 1                                '
'xcor 4                                '
'fs 3 2                                '
'plot 1                                '
'copy 1 2                              '
'xwin .3 20 1                          '
'plot 1                                '
'xcor 4                                '
'plot 1                                '
'print 1                               '
'copy 1 2                              '
'writ lh_t_s_cl                        '
'copy 3 1                              '
'plot 1                                '
'widt -30 90                           '
'phas ScS                              '
'cut 1                                 '
'plot 1                                '
'plot 1                                '
'plot 1                                '
'plot 1                                '
'fs 3 2                                '
'plot 1                                '
'print 1                               '
'                                      '
'                                      '
'plot 1                                '
'plot 1                                '
'plot 1                                '
'xcor 7                                '
'xcor 4                                '
'plot 1                                '
'xcor 4                                '
'plot 1                                '
'print 1                               '
'                                      '
'fs 3 2                                '
'plot 1                                '
'plot 1                                '
'fs 3 2                                '
'writ lh_t_scs_cl                      '
'add 1 2                               '
'cat 1 2                               '
'plot 1                                '
'plot 2                                '
'fs 3 2                                '
'copy 2 1                              '
'fs 3 2                                '
'plot 1                                '
'fs 3 2                                '
'plot 1                                '
'                                      '
'xcor 4                                '
'plot 1                                '
'plot 1                                '
'fs 3 2                                '
'plot 1                                '
'xcor 4                                '
'plot 1                                '
'print 1                               '
'                                      '
'fs 3 2                                '
'print 1                               '
'writ lh_t_s_scs_cl                    '
];                                      
