new_opt=[      
'orient tall            '
'corr                   '
'rm noinstr             '
'sort delta             '
'phas P                 '
'widt -300 1740         '
'cut 0                  '
'deme                   '
'tt P PP PcP PKPdf PKPab'
'tt S SS ScS SKSac SKKS '
'tt PcS ScP pP sP pPP   '
'tt sPP sS pS sSS pSS   '
'tt SP PS pSP sSP pPS   '
'tt sPS pPKPdf sPKPdf   '
'tt pPKPab sPKPab  PKKP '
'plot 1                 '
'tape .05               '
'copy 1 2               '
'deco l                 '
'widt -180 1560         '
'cut 1                  '
'plot 1                 '
];             
